name: Automated Build

on:
  push:
    branches: [ "llvm-swift-5.9-RELEASE" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Export variables
        run: export SKIP_XCODE_VERSION_CHECK=1

      - name: Configure and build LLVM and Clang
        run: cmake -S llvm -B build -G "Xcode" -DCMAKE_BUILD_TYPE=Release

      - name: Building LLVM
        run: cmake --build build -j$(nproc)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LLVM-Build
          path: build
  update-release:
    name: Release LLVM
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Delete old release
      uses: dev-drprasad/delete-tag-and-release@v0.2.1
      with:
        delete_release: true
        tag_name: ${{ github.ref_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Get artifacts
      uses: actions/download-artifact@v3
      with:
        name: LLVM-Build
    - name: Create new release
      uses: ncipollo/release-action@v1
      with:
        name: Rolling Release
        body: These are automatically updated builds of the latest commit.
        artifacts: "LLVM-Build"
        tag: ${{ github.ref_name }}
        token: ${{ secrets.GITHUB_TOKEN }}
